// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Secretaria.Domain.ADO;

namespace Secretaria.FrontEnd.Migrations
{
    [DbContext(typeof(SecretariaDbContext))]
    [Migration("20200425034434_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Secretaria.Domain.Escuela.Alumno", b =>
                {
                    b.Property<int>("legajo")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("legajoAlumno")
                        .HasColumnType("int");

                    b.Property<int>("Folio")
                        .HasColumnName("folio")
                        .HasColumnType("int");

                    b.Property<int>("Libro")
                        .HasColumnName("libro")
                        .HasColumnType("int");

                    b.Property<int?>("idCursoActual")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("idPersona")
                        .HasColumnType("int");

                    b.HasKey("legajo");

                    b.HasIndex("idCursoActual");

                    b.HasIndex("idPersona");

                    b.ToTable("Alumno");
                });

            modelBuilder.Entity("Secretaria.Domain.Escuela.Cursada", b =>
                {
                    b.Property<int>("idCursada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<short>("CicloLectivo")
                        .HasColumnName("cicloLectivo")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("Fecha")
                        .HasColumnName("fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("idCurso")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("legajoAlumno")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("idCursada");

                    b.HasIndex("idCurso");

                    b.HasIndex("legajoAlumno");

                    b.ToTable("Cursada");
                });

            modelBuilder.Entity("Secretaria.Domain.Escuela.Curso", b =>
                {
                    b.Property<int>("IdCurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idCurso")
                        .HasColumnType("int");

                    b.Property<byte>("Anio")
                        .HasColumnName("anio")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("Division")
                        .HasColumnName("division")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("IdCurso");

                    b.ToTable("Curso");
                });

            modelBuilder.Entity("Secretaria.Domain.Escuela.Seguimiento", b =>
                {
                    b.Property<int>("IdSeguimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idSeguimiento")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnName("fecha")
                        .HasColumnType("Date");

                    b.Property<string>("Observacion")
                        .IsRequired()
                        .HasColumnName("observacion")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<int?>("legajo")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("IdSeguimiento");

                    b.HasIndex("legajo");

                    b.ToTable("seguimiento");
                });

            modelBuilder.Entity("Secretaria.Domain.Escuela.TipoTutor", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnName("idTipoTutor")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Cadena")
                        .HasColumnName("tipoTutor")
                        .HasColumnType("varchar(45) CHARACTER SET utf8mb4")
                        .HasMaxLength(45);

                    b.HasKey("Id");

                    b.HasIndex("Cadena")
                        .IsUnique();

                    b.ToTable("tipoTutor");
                });

            modelBuilder.Entity("Secretaria.Domain.Escuela.Tutor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("idPersona")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<byte?>("idTipoTutor")
                        .IsRequired()
                        .HasColumnType("tinyint unsigned");

                    b.Property<int?>("legajo")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("idPersona");

                    b.HasIndex("idTipoTutor");

                    b.HasIndex("legajo");

                    b.ToTable("tutor");
                });

            modelBuilder.Entity("Secretaria.Domain.Faltas.AsistenciaCurso", b =>
                {
                    b.Property<int>("IdAsistenciaCurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idAsistenciaCurso")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnName("fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("idCurso")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<byte?>("idTipoFalta")
                        .IsRequired()
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("IdAsistenciaCurso");

                    b.HasIndex("idCurso");

                    b.HasIndex("idTipoFalta");

                    b.ToTable("AsisienciaCurso");
                });

            modelBuilder.Entity("Secretaria.Domain.Faltas.Falta", b =>
                {
                    b.Property<int>("IdFalta")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idFalta")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnName("fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Justificada")
                        .HasColumnName("justificada")
                        .HasColumnType("tinyint(1)");

                    b.Property<float>("ValorFalta")
                        .HasColumnName("valorFalta")
                        .HasColumnType("float");

                    b.Property<int?>("idAlumno")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("idCursada")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<byte?>("idTipoAusencia")
                        .IsRequired()
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte?>("idTipoFalta")
                        .IsRequired()
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("IdFalta");

                    b.HasIndex("idAlumno");

                    b.HasIndex("idCursada");

                    b.HasIndex("idTipoAusencia");

                    b.HasIndex("idTipoFalta");

                    b.ToTable("Falta");
                });

            modelBuilder.Entity("Secretaria.Domain.Faltas.TipoAusencia", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnName("idTipoAusencia")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Cadena")
                        .IsRequired()
                        .HasColumnName("tipoAusencia")
                        .HasColumnType("varchar(30) CHARACTER SET utf8mb4")
                        .HasMaxLength(30);

                    b.Property<float>("ValorFalta")
                        .HasColumnName("valorFalta")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("Cadena")
                        .IsUnique();

                    b.ToTable("TipoAusencia");
                });

            modelBuilder.Entity("Secretaria.Domain.Faltas.TipoFalta", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnName("idTipoFalta")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Cadena")
                        .HasColumnName("tipoFalta")
                        .HasColumnType("varchar(20) CHARACTER SET utf8mb4")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.HasIndex("Cadena")
                        .IsUnique();

                    b.ToTable("tipoFalta");
                });

            modelBuilder.Entity("Secretaria.Domain.InfoPersonal.Domicilio", b =>
                {
                    b.Property<int>("IdDomicilio")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idDomicilio")
                        .HasColumnType("int");

                    b.Property<int?>("Altura")
                        .HasColumnName("altura")
                        .HasColumnType("int");

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasColumnName("Calle")
                        .HasColumnType("varchar(45) CHARACTER SET utf8mb4")
                        .HasMaxLength(45);

                    b.Property<string>("CodigoPostal")
                        .HasColumnName("codigoPostal")
                        .HasColumnType("varchar(8) CHARACTER SET utf8mb4")
                        .HasMaxLength(8);

                    b.Property<string>("Departamento")
                        .HasColumnName("departamento")
                        .HasColumnType("varchar(3) CHARACTER SET utf8mb4")
                        .HasMaxLength(3);

                    b.Property<byte?>("Piso")
                        .HasColumnName("piso")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("idLocalidad")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("observacionDomicilio")
                        .HasColumnName("observacionDomicilio")
                        .HasColumnType("varchar(60) CHARACTER SET utf8mb4")
                        .HasMaxLength(60);

                    b.HasKey("IdDomicilio");

                    b.HasIndex("idLocalidad");

                    b.ToTable("Domicilio");
                });

            modelBuilder.Entity("Secretaria.Domain.InfoPersonal.Localidad", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnName("idLocalidad")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Cadena")
                        .HasColumnName("localidad")
                        .HasColumnType("varchar(45) CHARACTER SET utf8mb4")
                        .HasMaxLength(45);

                    b.HasKey("Id");

                    b.HasIndex("Cadena")
                        .IsUnique();

                    b.ToTable("Localidad");
                });

            modelBuilder.Entity("Secretaria.Domain.InfoPersonal.Nacionalidad", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnName("idNacionalidad")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Cadena")
                        .HasColumnName("nacionalidad")
                        .HasColumnType("varchar(45) CHARACTER SET utf8mb4")
                        .HasMaxLength(45);

                    b.HasKey("Id");

                    b.HasIndex("Cadena")
                        .IsUnique();

                    b.ToTable("Nacionalidad");
                });

            modelBuilder.Entity("Secretaria.Domain.InfoPersonal.Persona", b =>
                {
                    b.Property<int>("IdPersona")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idPersona")
                        .HasColumnType("int");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnName("apellido")
                        .HasColumnType("varchar(45) CHARACTER SET utf8mb4")
                        .HasMaxLength(45);

                    b.Property<string>("Mail")
                        .HasColumnName("mail")
                        .HasColumnType("varchar(60) CHARACTER SET utf8mb4")
                        .HasMaxLength(60);

                    b.Property<DateTime>("Nacimiento")
                        .HasColumnName("nacimiento")
                        .HasColumnType("Date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnName("nombre")
                        .HasColumnType("varchar(45) CHARACTER SET utf8mb4")
                        .HasMaxLength(45);

                    b.Property<int>("NroDocumento")
                        .HasColumnName("nroDocumento")
                        .HasColumnType("int");

                    b.Property<long?>("Telefono1")
                        .HasColumnName("telelfono1")
                        .HasColumnType("bigint");

                    b.Property<long?>("Telefono2")
                        .HasColumnName("telefono2")
                        .HasColumnType("bigint");

                    b.Property<int>("idDomicilio")
                        .HasColumnType("int");

                    b.Property<byte>("idNacionalidad")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("idTipoDocumento")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("IdPersona");

                    b.HasIndex("idDomicilio");

                    b.HasIndex("idNacionalidad");

                    b.HasIndex("idTipoDocumento");

                    b.ToTable("Persona");
                });

            modelBuilder.Entity("Secretaria.Domain.InfoPersonal.TipoDocumento", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnName("idTipoDocumento")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Cadena")
                        .HasColumnName("tipoDocumento")
                        .HasColumnType("varchar(45) CHARACTER SET utf8mb4")
                        .HasMaxLength(45);

                    b.HasKey("Id");

                    b.HasIndex("Cadena")
                        .IsUnique();

                    b.ToTable("TipoDocumento");
                });

            modelBuilder.Entity("Secretaria.Domain.Escuela.Alumno", b =>
                {
                    b.HasOne("Secretaria.Domain.Escuela.Curso", "CursoActual")
                        .WithMany("Alumnos")
                        .HasForeignKey("idCursoActual")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Secretaria.Domain.InfoPersonal.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("idPersona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Secretaria.Domain.Escuela.Cursada", b =>
                {
                    b.HasOne("Secretaria.Domain.Escuela.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("idCurso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Secretaria.Domain.Escuela.Alumno", "Alumno")
                        .WithMany("Cursadas")
                        .HasForeignKey("legajoAlumno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Secretaria.Domain.Escuela.Seguimiento", b =>
                {
                    b.HasOne("Secretaria.Domain.Escuela.Alumno", "Alumno")
                        .WithMany("Seguimientos")
                        .HasForeignKey("legajo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Secretaria.Domain.Escuela.Tutor", b =>
                {
                    b.HasOne("Secretaria.Domain.InfoPersonal.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("idPersona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Secretaria.Domain.Escuela.TipoTutor", "TipoTutor")
                        .WithMany()
                        .HasForeignKey("idTipoTutor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Secretaria.Domain.Escuela.Alumno", "Alumno")
                        .WithMany("Tutores")
                        .HasForeignKey("legajo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Secretaria.Domain.Faltas.AsistenciaCurso", b =>
                {
                    b.HasOne("Secretaria.Domain.Escuela.Curso", "Curso")
                        .WithMany("AsistenciaCurso")
                        .HasForeignKey("idCurso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Secretaria.Domain.Faltas.TipoFalta", "TipoFalta")
                        .WithMany("AsistenciaCurso")
                        .HasForeignKey("idTipoFalta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Secretaria.Domain.Faltas.Falta", b =>
                {
                    b.HasOne("Secretaria.Domain.Escuela.Alumno", "Alumno")
                        .WithMany("Faltas")
                        .HasForeignKey("idAlumno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Secretaria.Domain.Escuela.Cursada", "Cursada")
                        .WithMany("Faltas")
                        .HasForeignKey("idCursada")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Secretaria.Domain.Faltas.TipoAusencia", "TipoAusencia")
                        .WithMany("Faltas")
                        .HasForeignKey("idTipoAusencia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Secretaria.Domain.Faltas.TipoFalta", "TipoFalta")
                        .WithMany("Faltas")
                        .HasForeignKey("idTipoFalta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Secretaria.Domain.InfoPersonal.Domicilio", b =>
                {
                    b.HasOne("Secretaria.Domain.InfoPersonal.Localidad", "Localidad")
                        .WithMany()
                        .HasForeignKey("idLocalidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Secretaria.Domain.InfoPersonal.Persona", b =>
                {
                    b.HasOne("Secretaria.Domain.InfoPersonal.Domicilio", "Domicilio")
                        .WithMany()
                        .HasForeignKey("idDomicilio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Secretaria.Domain.InfoPersonal.Nacionalidad", "Nacionalidad")
                        .WithMany()
                        .HasForeignKey("idNacionalidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Secretaria.Domain.InfoPersonal.TipoDocumento", "TipoDocumento")
                        .WithMany()
                        .HasForeignKey("idTipoDocumento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
